"""
Console command -> parameter-name-list reference, used for autocomplete
in both apps' console UIs (server's local ConsoleWindow, client's
RemoteConsoleWindow and TavernKeeper). Not guaranteed 100% exhaustive or
perfectly current with every game version.
"""
CONSOLE_COMMANDS = {
    "agents print": [],
    "audio microphone mute": [],
    "audio microphone unmute": [],
    "chunks check-wipe": [],
    "chunks entities": ["chunk"],
    "chunks force-load": ["chunk", "isForceLoaded"],
    "chunks info": ["chunk"],
    "chunks loadall": ["loaded"],
    "chunks merge": ["prefabHashes"],
    "chunks print-all": [],
    "chunks print-loaded": [],
    "chunks set-load": ["loadDistance", "unloadDistance"],
    "chunks set-receive-count": ["receiveAmount"],
    "chunks set-receive-ms": ["receiveDuration"],
    "chunks set-static-load": ["isLoading"],
    "chunks set-static-per-frame": ["numberToLoadPerFrame"],
    "chunks set-static-sequence": ["loadSequentially"],
    "chunks set-sync-amount": ["syncAmount"],
    "chunks set-sync-interval": ["interval"],
    "chunks set-timed": ["processingPercent", "maxAllowance", "minNeeded"],
    "chunks wipe": ["chunk"],
    "debug count": ["prefab"],
    "debug count-all": [],
    "debug count-behaviours": ["behaviourName", "isEnabled"],
    "debug count-scripts": ["typeName", "isCountingResources", "isFindingChildren"],
    "debug entities": [],
    "debug entity-health": [],
    "debug export-navmesh": ["output"],
    "debug fixedtime": [],
    "debug lag": ["targetFPS"],
    "debug load-marker": ["player"],
    "debug nameid": ["id"],
    "debug open-logs": [],
    "debug prefabcounts": [],
    "debug print-names": ["scriptName"],
    "debug remote-console": [],
    "debug server-stats": [],
    "debug set": ["player", "index"],
    "debug static check-current": [],
    "debug static fix": ["hashes"],
    "debug static list": [],
    "debug static modify": ["hash", "state"],
    "debug tracking get": ["name"],
    "debug tracking remove": ["name"],
    "debug tracking track": ["entityId", "name"],
    "debug turabada-ai": [],
    "festivities info": ["festivity"],
    "festivities list": [],
    "festivities start": ["festivity"],
    "festivities stop": ["festivity"],
    "game connect": ["serverIdentifier", "playerMode"],
    "game connect-player": ["player", "playerMode"],
    "game create-server": ["serverName", "sceneIndex", "region"],
    "game delete-save": ["serverIdentifier"],
    "game find": ["name"],
    "game ip-local": ["sceneIndex", "playerMode", "port"],
    "game join-ip": ["serverIp", "sceneIndex", "playerMode", "port"],
    "game join-server": ["serverIdentifier", "playerMode"],
    "game list-recent": [],
    "game local-test": ["serverIdentifier", "playerMode"],
    "game local-test-scene": ["scene", "playerMode"],
    "game show-all": [],
    "game show-discover": [],
    "game show-online": [],
    "game show-open": [],
    "game show-owned": [],
    "game show-public": [],
    "game start-local": ["sceneIndex", "isExternalLaunch", "port", "isHeadless", "isRunningLocally"],
    "game start-server": ["server", "isExternalLaunch", "port", "isHeadless", "isRunningLocally"],
    "game startclean": ["server", "isExternalLaunch", "port", "isHeadless", "isRunningLocally"],
    "game stop-mode": [],
    "global-population list": [],
    "global-population set-size": ["population", "maxSpawned"],
    "global-population spawned": ["population"],
    "global-population teleport": ["player", "population", "distanceAway"],
    "global-population teleport-to": ["player", "population", "index", "distanceAway"],
    "help": ["path"],
    "help full": ["path"],
    "help modules": [],
    "help search": ["searchString"],
    "impacts sync": ["isSubscribing"],
    "info": [],
    "info cli": [],
    "info player-mode": [],
    "info server": [],
    "info system": [],
    "info user": [],
    "info version": [],
    "landmarks enable": ["enabled"],
    "landmarks load-enabled": ["isLoading"],
    "leaderboard create": ["courseName", "isLowest"],
    "leaderboard get-rank": ["courseName"],
    "leaderboard list": [],
    "leaderboard remove-checkpoint": ["courseName", "isBeginning"],
    "leaderboard set-board": ["courseName"],
    "leaderboard set-checkpoint": ["courseName", "isBeginning"],
    "login": ["username", "password"],
    "logout": [],
    "logs": [],
    "logs change-target": ["targetName", "minLevel", "maxLevel", "loggerNamePattern"],
    "logs config": ["isPrintingAll"],
    "logs destroy-trace": ["isEnabled"],
    "logs warn-stack": ["isEnabled"],
    "maintenance garbage": [],
    "maintenance resources": [],
    "microtutorial active": [],
    "microtutorial exit": ["player"],
    "microtutorial list": [],
    "microtutorial next-step": ["player"],
    "microtutorial set-log-level": ["level"],
    "microtutorial start": ["player", "tutorialSettings"],
    "mods": [],
    "mods add": ["name", "content", "isOverride"],
    "mods path": [],
    "mods refresh": [],
    "mods remove": ["name"],
    "mods restart": ["name"],
    "mods start": ["name"],
    "mods stop": ["name"],
    "player check-stat": ["player", "stat"],
    "player count": [],
    "player cripple": ["players"],
    "player detailed": ["player"],
    "player get-home": ["player"],
    "player getdamagemulti": [],
    "player god-mode": ["players", "isOn"],
    "player id": ["username"],
    "player inventory": ["players"],
    "player inventory load": ["user", "save"],
    "player inventory save": ["user"],
    "player kick": ["players", "reason"],
    "player kill": ["players"],
    "player list": [],
    "player list-detailed": [],
    "player list-stats": ["player"],
    "player message": ["players", "message", "duration"],
    "player modify-stat": ["players", "statDefinition", "valueModifier", "duration", "isMultiplier"],
    "player progression allxp": ["players", "xp"],
    "player progression buyskill": ["slotIndex", "isConsumingExperience"],
    "player progression checkallxp": ["players"],
    "player progression clearall": ["players"],
    "player progression clearpath": ["player", "path"],
    "player progression list": [],
    "player progression offlinelevels": ["userInfo", "path", "levels"],
    "player progression pathlevelup": ["players", "path"],
    "player progression pathxp": ["players", "path", "xp"],
    "player progression printofflinelevels": [],
    "player progression showskills": ["player"],
    "player set-home": ["players", "home"],
    "player set-stat": ["players", "statDefinition", "value", "applicationType"],
    "player set-unlock": ["players", "unlock", "isUnlocked"],
    "player setdamagemulti": ["multiplier"],
    "player teleport": ["players", "target"],
    "player unlock-cancel": ["player"],
    "player unlock-check": ["player", "unlock"],
    "player username": ["userId"],
    "profiling cleanslatememory": ["name", "path"],
    "profiling dumpsize": [],
    "profiling heapdump": [],
    "profiling memorydump": ["name", "path"],
    "profiling sample": ["name", "path", "frames", "postAction"],
    "progress fill-book": ["collection"],
    "progress fill-books": [],
    "progress fillcaveteleporter": ["layer", "fuelQuantity"],
    "progress fillcommunityboxes": [],
    "progress finishboxes": [],
    "progress forgeall": [],
    "progress generatecaves": ["layer", "debugCallback"],
    "progress list-books": [],
    "progress listcaveteleporter": [],
    "progress repaircaveteleporters": ["layer"],
    "quality dynamic-load-multiplier": ["loadMultiplier"],
    "quality lod-bias": ["lodbias"],
    "quality static-load-multiplier": ["loadMultiplier"],
    "quit": [],
    "recent-players test-record": ["name", "id", "interactionType"],
    "repair-box": ["player", "item1", "count1", "item2", "count2", "item3", "count3", "output", "localSpawnPosition"],
    "repair-box list-items": [],
    "repeat": ["count", "intervalInSeconds", "isLoggingProgress"],
    "repeat last": [],
    "repeat stop": ["id"],
    "repeat stopall": [],
    "report-players create": ["userId", "type", "serverId"],
    "report-players list": ["statusFilter", "serverFilter"],
    "save": [],
    "save backup": ["isInstant"],
    "save full-wipe": [],
    "save now": [],
    "save player-wipe": ["user", "isWipingLockbox", "isWipingATM", "isWipingPostbox", "isWipingLandmarks", "isWipingMap"],
    "save player-wipe-all": ["isWipingATM", "isWipingPostbox", "isWipingLandmarks", "isWipingMap"],
    "save wipe": ["isSettingOffline"],
    "save wipe-forced": ["keepPlayers"],
    "save wipe-storage": [],
    "save wipecache": ["isSettingOffline"],
    "save wipecaves": [],
    "select": ["identifier"],
    "select destroy": [],
    "select find": ["player", "distance"],
    "select get": ["identifier"],
    "select look-at": ["player", "isRotatingAllAxis"],
    "select move back": ["amount"],
    "select move down": ["amount"],
    "select move exact": ["position"],
    "select move forward": ["amount"],
    "select move left": ["amount"],
    "select move right": ["amount"],
    "select move up": ["amount"],
    "select prefab": ["prefab", "player"],
    "select rotate exact": ["rotation"],
    "select rotate pitch": ["degrees"],
    "select rotate roll": ["degrees"],
    "select rotate yaw": ["degrees"],
    "select snap-ground": [],
    "select snap-to": ["identifier"],
    "select tostring": [],
    "select unselect": [],
    "server migrate": ["secondsLeftUntilTermination"],
    "server proxy": ["serverId", "proxiedCommand"],
    "server start": ["serverId", "isExternalLaunch", "port", "isHeadless", "isRunningLocally"],
    "settings changesetting": ["settingsTarget", "setting", "value"],
    "settings disable-board": [],
    "settings enable-board": [],
    "settings heat": ["multiplier"],
    "settings infoboard": ["identifier", "value"],
    "settings infoboard-list": [],
    "settings list": ["settingsTarget"],
    "settings population check-time": ["population"],
    "settings population reset-time": ["population"],
    "settings population set-time": ["population", "timeInSeconds"],
    "settings possible": ["settingsTarget", "setting"],
    "settings reset": [],
    "settings save": [],
    "settings settoggle": ["setting", "isOn"],
    "settings toggle": ["setting"],
    "social addfriend": ["player"],
    "social listfriends": ["user"],
    "social removefriend": ["player"],
    "spawn": ["players", "prefab", "arguments"],
    "spawn exact": ["position", "rotation", "prefab", "arguments"],
    "spawn find": ["name"],
    "spawn infodump": [],
    "spawn list": [],
    "spawn list materials": [],
    "spawn local": ["prefab"],
    "spawn moulds": ["players", "prefab"],
    "spawn moulds list": [],
    "spawn multi": ["players", "name", "args"],
    "spawn package drop": ["players", "arguments"],
    "spawn package list": [],
    "spawn pages list": [],
    "spawn pages spawn": ["players", "collection"],
    "spawn population": ["player", "population", "populationType", "size", "startingPopulation", "maxPopulation"],
    "spawn population-list": [],
    "spawn string": ["players", "value"],
    "spawn string-raw": ["value"],
    "time": [],
    "time future": ["progress", "measure"],
    "time keywords": [],
    "time ofday": ["isNormalised"],
    "time set": ["time"],
    "time toggle": [],
    "trade atm add": ["user", "quantityToAdd"],
    "trade atm get": ["user"],
    "trade atm set": ["user", "quantity"],
    "trade empty": [],
    "trade post": ["user", "prefab", "arguments"],
    "trade post-string": ["user", "value"],
    "trial list": [],
    "trial players": ["key"],
    "trial progress": ["key"],
    "trial reset": ["key"],
    "users statistics": ["user"],
    "wacky chisel-deck": [],
    "wacky cleanplayerbody": ["player"],
    "wacky cleanplayerstate": ["player"],
    "wacky destroy": ["id"],
    "wacky destroy-free": ["prefab", "chunks"],
    "wacky destroyall": ["prefab"],
    "wacky inputscale": ["scale"],
    "wacky marcopolo": ["player"],
    "wacky ow-loot": [],
    "wacky replace": ["id"],
    "wacky replace-selected": [],
    "wacky setvolume": ["local", "remote"],
    "wacky smelter": [],
    "websocket subscribe": ["eventType"],
    "websocket subscriptions": [],
    "websocket unsubscribe": ["eventType"],
    "world caves reset": [],
    "world caves teleport": ["players", "layer"],
    "world forest info": ["forest"],
    "world forest list": [],
    "world forest reset": ["forest"],
    "world forest teleport": ["players", "forest", "nodeIndex"],
}

